version: '3.8'

services:
  api:
    build: .
    container_name: nestjs_api
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy  # Wait until DB is fully ready
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
